name: test

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run deployment script
        env:
          WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
        run: node MMdeploy.js
